### ISSUE TITLE
any docs?

### ISSUE THREAD

**Issue by lorvent** [chalkygames123/front-end-template#182]
Hello,

do you have any guide to begin with ?

like how to compile multiple sass files etc.

Ex: earlier, i have used laravel-mix, which has option like `gulp.sass(src,dest);`, do we have something like that here?

thanks.

**Comment by chalkygames123** [comment]
I am mainly developing this template for my works.

I want to improve the documentation in the future, but for now, it is minimal. And I sometimes update the source code aggressively without any notice, versioning, or release notes.

This template is a simple combination of third-party tools and can be easily customized. But if you don't understand how to configure them (especially gulp and webpack) well, It is not recommended to use it.

However, if you want to build a typical website, this template will be useful.

I've never used Laravel Mix, but this template can compile multiple Sass files automatically without any configuration.

For example, there are `assets/styles/pages/common/style.scss` and `assets/styles/pages/index/style.scss`. The template just compiles them as `dist/assets/styles/pages/common/style.css` and `dist/assets/styles/pages/index/style.scss` (`dist` is the default output directory of build artifacts).

If you want to change the output directory, you can do that by updating `config.js` like this:

```
config.load({
  distDir: 'path/to/your/dist'
})
```

Alternatively, you can specify the output directory from the command line like this:

```
$ yarn build --dist-dir=path/to/your/dist
```

To see other options, look at the `config-schema.js`. Or, uncomment this line and run any task: https://github.com/chalkygames123/front-end-template/blob/5700411e44d71933b750dd7f1929d92a1df6574a/config.js#L4

Questions are always welcome.

**Comment by lorvent** [comment]
Hello,
thanks for the response.

i have developed my own gulp-starter long back but yours looking much better so wanted to use this.

i will try to implement this and get back to you, if i need any more help.
