### ISSUE TITLE
combining multiple css files into one

### ISSUE THREAD

**Issue by lorvent** [chalkygames123/front-end-template#185]
Hello,
does it has option to combine multiple css files into one?

also combining multiple js files into single js file?

thanks.

**Comment by chalkygames123** [comment]
I'm not sure about what you're trying to do, but isn't that what you can achieve with [Sass's `@import` rule](http://www.sass-lang.com/documentation/at-rules/import)?

JavaScript also has a similar feature: [`import` statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import).

**Comment by lorvent** [comment]
Hello,
lets say,
i want to include `a.css, b.css, c.css` in every page, instead of that, i want to combine them into `final.css`

i.e. concatination

is that possible?

like https://laravel-mix.com/docs/5.0/concatenation-and-minification#combine-files

**Comment by chalkygames123** [comment]
In cases where you need to combine text files, you can use the [gulp-concat](https://github.com/gulp-community/gulp-concat) package.

**Comment by lorvent** [comment]
i mostly need to combine css and js files.

**Comment by chalkygames123** [comment]
Yes, they are text files, and the plugin can handle them. Use it in your `styles` and `scripts` tasks as you like.

However, it seems that your problem can also solve with Nunjucks' [extends](https://mozilla.github.io/nunjucks/templating.html#extends) or [include](https://mozilla.github.io/nunjucks/templating.html#include).

**Comment by lorvent** [comment]
nunjucks extends, include purpose is different imo.

i will try with gulp-concat.

thanks.
