### ISSUE TITLE
browserSync not working in .njk files

### ISSUE THREAD

**Issue by lorvent** [chalkygames123/front-end-template#194]
Hello,
Today i wanted to try your project,

but when i make changes to default layout file or index.njk, changes are not being shown at `localhost:3000`

only when i quit and run `yarn dev` again, i can see changes but again, next changes are not being shown.

i.e. it is serving from `dist` folder but it should pick up changes as we make ,

or I am doing something wrong or it is working **as intended** ?

**Comment by chalkygames123** [comment]
Are you on the latest source? It seems you are experiencing a bug that already resolved.

**Comment by lorvent** [comment]
Yes, i just cloned the repo and tried it.

**Comment by lorvent** [comment]
I just tried using WSL and it is working fine

but on windows terminal, it is not working.

**Comment by chalkygames123** [comment]
Does "windows terminal" mean Command Prompt (cmd.exe)? 

I don't have time now, but I'll dig into the issue in a few days.

**Comment by lorvent** [comment]
Hello,

i have tried cmd.exe and powershell, with both browsersync is not working.

**Comment by chalkygames123** [comment]
I have confirmed that the problem can be reproduced in my environment, but the cause is still unclear.

I will look into more details at the weekend.

**Comment by chalkygames123** [comment]
I fixed the problem. Please check it.

**Comment by lorvent** [comment]
Hello,

I can confirm it is working fine.

however stylelink showing one error `stylelint: Undefined rule unicode-bom`
hope you are aware of it.

**Comment by chalkygames123** [comment]
Where do you see that error? If it is VS Code, you should use the official stylelint extension ([stylelint.vscode-stylelint](stylelint.vscode-stylelint)) since `shinnn.stylelint` is now outdated & unpublished.

**Comment by lorvent** [comment]
i was using someother stylelint and installing official one removed the warning.

eventhough i won't be using your css code etc (and replace it with bootstrap),
i found something.

if i add something like 'welcome' to index.njk, it is adding horizontal scrollbar
![image](https://user-images.githubusercontent.com/3512953/72278371-e0385980-3659-11ea-9c0a-8d8db6617400.png)

**Comment by chalkygames123** [comment]
Probably It's a normal result of the `html` element having `min-width: 1280px`.

**Comment by lorvent** [comment]
Ahhh! ok.
